apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: inventario
type: Opaque
stringData:
  SQL_USERNAME: "<usuario-sql>"
  SQL_PASSWORD: "<contraseña-sql>"
  SPRING_LDAP_USERNAME: "<usuario-ldap>"
  SPRING_LDAP_PASSWORD: "<contraseña-ldap>"
  SPRING_LDAPADMIN_USERNAME: "<usuario-ldap-admin>"
  SPRING_LDAPADMIN_PASSWORD: "<contraseña-ldap-admin>"
  SPRING_DATA_MONGODB_URI: "mongodb://<usuario-mongo>:<contraseña-mongo>@inventario-db:27017/inventario"
