apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: inventario
type: Opaque
stringData:
  SQL_USERNAME: "<usuario-sql>"
  SQL_PASSWORD: "<contraseña>"
  LDAP_USER: "<usuario-ldap>"
  LDAP_PASSWORD: "<contraseña>"
