apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: inventario
type: Opaque
stringData:
  MONGO_USER: app-inventario
  MONGO_PASS: inventario123 #cambiar por la que se defina Agus
