apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: inventario
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "<usuario-root-mongo>"
  MONGO_INITDB_ROOT_PASSWORD: "<contraseña-root-mongo>"
