apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: inventario
data:
  LDAP_HOST: "10.10.10.10"
  LDAP_PORT: "389"
  LDAP_BASE: "dc=itu,dc=local"
  KRB5_CONF: "/etc/krb5.conf"
  LOGIN_CONF: "/etc/login.conf"
  SQL_HOST: "ubicacion-db"
  SQL_PORT: "1433"
  SQL_DB: "InventarioITU"
  MONGO_HOST: "inventario-db"
  MONGO_PORT: "27017"
  MONGO_DB: "inventario"

