apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: inventario
data:
  LDAP_HOST: "ldap-service"
  LDAP_PORT: "389"
  LDAP_BASE: "dc=itu,dc=local"
  SQL_HOST: "ubicacion-db"
  SQL_PORT: "1433"
  SQL_DB: "InventarioITU"
  MONGO_HOST: "inventario-db"
  MONGO_PORT: "27017"
  MONGO_DB: "inventario"
  MONGO_URI: "mongodb://app-inventario:password123@inventario-db:27017/inventario?authSource=inventario"
  MONGO_SERVICE_URL: "http://backend-mongo:8080"
