apiVersion: v1
kind: ConfigMap
metadata:
  name: krb5-config
  namespace: inventario
data:
  krb5.conf: |
    [libdefaults]
        default_realm = ITU.LOCAL
        dns_lookup_realm = false
        dns_lookup_kdc = false
        ticket_lifetime = 24h
        forwardable = true

    [realms]
        ITU.LOCAL = {
            kdc = 10.10.10.10
            admin_server = 10.10.10.10
        }

    [domain_realm]
        .itu.local = ITU.LOCAL
        itu.local = ITU.LOCAL
  login.conf: |
    SQLJDBCDriver {
        com.sun.security.auth.module.Krb5LoginModule required
        useKeyTab=true
        keyTab="/etc/krb5.keytab"
        principal="svc_inventario@ITU.LOCAL"
        storeKey=true
        debug=false;
    };
