apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-mongo
  namespace: inventario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-mongo
  template:
    metadata:
      labels:
        app: backend-mongo
    spec:
      serviceAccountName: sa-backend
      containers:
        - name: backend-mongo
          image: ghcr.io/romis2799/backend-mongo:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URI
