apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: inventario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      serviceAccountName: sa-backend
      containers:
        - name: backend-api
          image: backend-api:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            # Credenciales SQL (desde Secret)
            - name: SQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SQL_USERNAME
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SQL_PASSWORD
            # Credenciales LDAP (desde Secret)
            - name: LDAP_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: LDAP_USER
            - name: LDAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: LDAP_PASSWORD
            # Config no sensible (desde ConfigMap)
            - name: LDAP_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LDAP_HOST
            - name: LDAP_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LDAP_PORT
            - name: LDAP_BASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LDAP_BASE
            - name: KRB5_CONF
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KRB5_CONF
            - name: LOGIN_CONF
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOGIN_CONF
            - name: SQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SQL_HOST
            - name: SQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SQL_PORT
            - name: SQL_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SQL_DB
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URI
            - name: SPRING_PROFILES_ACTIVE
              value: "kerberos"
          volumeMounts:
            - name: krb5-config-vol
              mountPath: /etc/krb5.conf
              subPath: krb5.conf
            - name: krb5-config-vol
              mountPath: /etc/login.conf
              subPath: login.conf
            - name: keytab-vol
              mountPath: /etc/krb5.keytab
              subPath: krb5.keytab
      volumes:
        - name: krb5-config-vol
          configMap:
            name: krb5-config
        - name: keytab-vol
          secret:
            secretName: krb5-keytab
