apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: inventario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      serviceAccountName: sa-backend
      containers:
        - name: backend-api
          image: ghcr.io/romis2799/backend-api:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SQL_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SQL_PASSWORD
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
            - name: SPRING_LDAP_URLS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_LDAP_URLS
            - name: SPRING_LDAP_BASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_LDAP_BASE
            - name: SPRING_LDAP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: LDAP_USER
            - name: SPRING_LDAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: LDAP_PASSWORD
            - name: SPRING_LDAPADMIN_URLS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_LDAPADMIN_URLS
            - name: SPRING_LDAPADMIN_BASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_LDAPADMIN_BASE
            - name: SPRING_LDAPADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: LDAP_ADMIN_USER
            - name: SPRING_LDAPADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: LDAP_ADMIN_PASSWORD
