apiVersion: v1
kind: Service
metadata:
  name: ldap-service
  namespace: inventario
spec:
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
  type: Cluster0IP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ldap-service
  namespace: inventario
subsets:
  - addresses:
      - ip: 10.10.10.10
    ports:
      - port: 389
