apiVersion: v1
kind: Service
metadata:
  name: ldap-service
  namespace: inventario
spec:
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ldap-service
  namespace: inventario
subsets:
  - addresses:
      - ip: 172.22.74.191
    ports:
      - port: 389
