apiVersion: v1
kind: Service
metadata:
  name: ubicacion-db
  namespace: inventario
spec:
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ubicacion-db
  namespace: inventario
subsets:
  - addresses:
      - ip: 172.22.74.186
    ports:
      - port: 1433
